name = "Deepmod"
author = "TheWander02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f894aa716e36ab7d4dc390c579fbc39c5284a6ff5d50044e745a985f9c4977fb"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.x", "add"]
