name = "Deepmod"
author = "TheWander02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5b63173b2b90c775843eb3b8bf1898415ac5d888d62720ea49fea6808cffec4"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
