name = "Deepmod"
author = "TheWander02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78efc3f4f47fb6219a3e6bef06c2ee6609bb6b2e3e454c01259681255dfaa3c0"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.x", "add"]
