name = "Deepmod"
author = "TheWander02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cf9337b19d85fca8495bf88273751aea782a30852243184a2c3f2511ad153c7"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
