name = "Deepmod"
author = "TheWander02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d26e82cd3769d0125c66ba9e104f5f26e49b8151bb19e8fe898da4524f79d347"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.x", "add"]
