name = "Deepmod"
author = "TheWander02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95f84e756e232c5c2bdd17beae3fc280b16298849f56cbac57af2d7c5087a264"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.x", "add"]
