name = "Deepmod"
author = "TheWander02"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbc34c55e2028a2f907cfb421c434a6d9868ce98168e21e8a058f53862ccbb11"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.x", "add"]
